In [4]:
import numpy as np

In [5]:
myList = [1, 2, 3, 4, 5]
type(myList)

list

In [7]:
a1 = np.array(myList)
a1

array([1, 2, 3, 4, 5])

In [15]:
a1.shape

(5,)

In [13]:
myList2 = [[1, 2, 3], [4, 5, 6]]

In [14]:
a2 =np.array(myList2)
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a2.shape

(2, 3)

In [17]:
a2.ndim

2

In [21]:
np.arange(10, 101, 2)

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.full(10, 10)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [28]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
arr.reshape((6, 2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [30]:
arr.reshape((4, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
arr.reshape((-1, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [33]:
arr.reshape((6, -1))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
arr[2]

2

In [36]:
arr[2:8]

array([2, 3, 4, 5, 6, 7])

In [37]:
arr % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False])

In [38]:
arr[arr % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [40]:
(arr % 2 == 0) & (arr % 3 == 0)

array([ True, False, False, False, False, False,  True, False, False,
       False, False, False])

In [41]:
arr[(arr % 2 == 0) & (arr % 3 == 0)]

array([0, 6])

In [43]:
arr[2:8] = 100

In [44]:
arr

array([  0,   1, 100, 100, 100, 100, 100, 100,   8,   9,  10,  11])